# Generated by Django 2.0 on 2019-01-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='school',
        ),
        migrations.AddField(
            model_name='study',
            name='school',
            field=models.CharField(default='LCH', max_length=60),
            preserve_default=False,
        ),
    ]
