# Generated by Django 2.0 on 2019-01-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190103_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='school',
        ),
        migrations.AddField(
            model_name='study',
            name='school',
            field=models.ManyToManyField(related_name='studies', to='app.School'),
        ),
    ]
