# Generated by Django 2.0 on 2019-01-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190105_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='school',
        ),
        migrations.AddField(
            model_name='study',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='study',
            name='label',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='post_box',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='post_box',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='frequenter',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
        migrations.AddField(
            model_name='frequenter',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Study'),
        ),
    ]
