# Generated by Django 2.0 on 2019-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190107_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='serial_number',
            field=models.CharField(help_text='Entrez un matricule sous le format 00A0000AA', max_length=20, unique=True),
        ),
    ]
